### ISSUE TITLE
Ошибка при расчёте секунд

### ISSUE THREAD

**Issue by kaineer** [lp-cast/3lp.me#1]
https://github.com/lp-cast/3lp.me/blob/8832f6e87be4be7f862d934a9693ee8be3fc95c0/src/blocks/player/player.js#L9

Тут либо использовать `3600` вместо `60`, либо вообще не закладываться на главы, которые будут (в смысле, никогда не будут) начинаться после отметки `01:00:00` и строку эту убрать.

А ещё очень занятно выглядит сочетание `[...players]` и `var` в коде. Хотя, разумеется, после обработки транспилером и минификатором это уже никого не волнует :)

**Comment by pepelsbey** [comment]
А можешь оформить в пулреквест? Писалось на коленке :) Спасибо!

**Comment by kaineer** [comment]
Окей.

**Comment by kaineer** [comment]
Готово.
