### ISSUE TITLE
Ссылки на внешние ресуры без target=_blank

### ISSUE THREAD

**Issue by itlen** [lp-cast/3lp.me#2]
При прослушивании, клик на любую ссылку открывает ресурс в текущей вкладке: при возврате не понимаешь на каком месте подкаста остановился.

**Comment by pepelsbey** [comment]
Спорная штука. Плеер специально сделан самый примитивный, мы всё-таки рассчитываем, что публика будет слушать нас в более удобных местах, где сохраняется прогресс между прослушиваниями, где можно установить скорость и прочие вещи.

У нас в какой-то момент появятся внутренние страницы и при переходе между ними запоминание или даже продолжать воспроизведение — это гораздо серьёзнее, чем хотелось бы заморачиваться.

Моя личная политика насчёт `target=_blank` такая: не ставить, если только это в самом деле очень-очень нужно. Люди в интернете знают, что если нажать на ссылку, то перейдёшь на другой сайт. А если выбрать «открыть в отдельной вкладке» (или нажать клавишу), то сохранишь текущий. Сайты, которые множат вкладки, желая оставить себя на вкладке, подбешивают, я этого не ожидаю.

Так что даже не знаю.

**Comment by pepelsbey** [comment]
На том и порешили
