### ISSUE TITLE
Мертвый скролл

### ISSUE THREAD

**Issue by itlen** [lp-cast/3lp.me#4]
Фокус на тэг <audio> морозит скролл страницы с клавиатуры. Chrome, Ubunta 16.

**Comment by itlen** [comment]
На тэг audio

**Comment by pepelsbey** [comment]
Фокус куда? В целом, это обычное поведение — любой сфокусированный элемент забирает события с клавиатуры.

**Comment by pepelsbey** [comment]
В случае с audio, стрелки регулируют громкость, если я правильно понимаю, то есть это нормальное поведение.

**Comment by itlen** [comment]
Да, но фокус на ползунок таймлайна делает то же самое (вправо/влево). Фокус на ползунок громкости делает то же самое (вверх/вниз). При фокусе на audio имхо не очевидны оба действия + неудобства от пропажи скрола с клавиатуры.

**Comment by pepelsbey** [comment]
Именно так работают встроенные браузерные элементы audio и video на всех остальных сайтах в интернете. То есть мы не делали ничего дополнительно и если мы начнём менять поведение по умолчанию (я даже не уверен, что это возможно), то это будет непривычно и неудобно пользователям.

То есть это не к нам, это к браузеру :)
